### ISSUE TITLE
Support Cordova sqlite plugin

### ISSUE THREAD

**Issue by brody2consult** [MetaMemoryT/websql-promise#1]
I may issue a PR for this. A couple of other things:

The real problem you are solving is dealing with asynchronous transactions. It would be nice to provide a wrapper that takes a db object that is already created with window.openDatabase() or window.sqlitePlugin.openDatabase().

It would also be good to have an automatic test suite. Again, I may issue a PR if I get some spare cycles.

**Comment by MetaMemoryT** [comment]
Great suggestions, I am working on a test suite

**Comment by MetaMemoryT** [comment]
I have created an initial test suite.  

The library should be compatible with https://github.com/litehelpers/Cordova-sqlite-storage now.

A new release has been created.

Please close this issue if your concerns have been met.

**Comment by brody2consult** [comment]
Thanks, this is really awesome! I just added a link to both https://github.com/litehelpers/Cordova-sqlite-storage and https://github.com/litehelpers/Cordova-sqlcipher-adapter.

**Comment by brody2consult** [comment]
Helps with litehelpers/Cordova-sqlite-storage#347, which is what triggered this issue.
